### ISSUE TITLE
Install issue on centos 7

### ISSUE THREAD

**Issue by almightyfoon** [cloudbase/PyMI#33]
When trying to pip install PyMI I get the following error:

pip install PyMI
Collecting PyMI
  Using cached PyMI-1.0.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-AEJG6H/PyMI/setup.py", line 17, in <module>
        version=get_git_version(),
      File "/tmp/pip-build-AEJG6H/PyMI/setup.py", line 7, in get_git_version
        g = git.Git(".")
    AttributeError: 'module' object has no attribute 'Git'

This is on Python 2.7.5, using 3.6 I see an error running git describe as my code doesn't have any tags.

**Comment by claudiubelu** [comment]
Hi,

PyMI has wheels published on pypi [1], which are used when installing PyMI on Windows hosts. There aren't any wheels for Linux, which means that pip will try to download the source and compile itself.

There aren't any Linux wheels because it isn't a supported OS at the moment, but may be added in the future.

[1] https://pypi.python.org/pypi/PyMI/1.0.4
